name: Build iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Godot
      run: |
        wget https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_macos.universal.zip
        unzip Godot_v4.5-stable_macos.universal.zip -d godot
        sudo mv godot/Godot.app /Applications/Godot.app
        sudo ln -s /Applications/Godot.app/Contents/MacOS/Godot /usr/local/bin/godot

    - name: Download Godot Export Templates
      run: |
        mkdir -p ~/Library/Application\ Support/Godot/export_templates/4.5.stable
        cd ~/Library/Application\ Support/Godot/export_templates/4.5.stable
        wget https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_export_templates.tpz
        unzip Godot_v4.5-stable_export_templates.tpz
        cd templates
        mv * ..
        cd ..
        rm -rf templates
        ls

    - name: Create build directory
      run: mkdir -p build

    - name: Export iOS project
      run: godot --headless --export-release "iOS" build/atestathorror.xcodeproj
        
    - name: Set iOS Deployment Target
      run: sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = 12.0;/IPHONEOS_DEPLOYMENT_TARGET = 14.0;/' build/atestathorror.xcodeproj/project.pbxproj

    - name: Build iOS project
      run: xcodebuild -project build/atestathorror.xcodeproj -scheme atestathorror -configuration Release -archivePath build/atestathorror.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

    - name: Export IPA
      run: | 
        cd build
        cd atestathorror.xcarchive
        cd Products
        cd Applications
        mkdir Payload
        mv atestathorror.app Payload/
        zip -r atestathorror.ipa Payload/
        mv atestathorror.ipa ../../..
    - name: Upload IPA to GitHub Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: atestathorror-ipa
        path: atestathorror.ipa
